blaze:
  sendAmountLimit: 10000

  blackListedPeople:
    lastnames:
      Smith, Brown, Tremblay

  MoneyLaundering:
    lastnames:
      Martin, Roy




#relativePath: com.system.blaze.customException
#
#test2: "${relativePath}.BlacklistException"



#error_map:
#    com.system.blaze.customException:
#      {BlacklistException: "0010", MoneyLaunderingException : "0011"}